# Generated by Django 3.2.16 on 2022-11-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_advuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
